crypto-org-chain/chain-docs

docs/getting-started/croeseid-testnet.md
- Update the genesis.json link to the renamed repo;
- Generic sha256sum genesis check;
- We will be using `testnet-croeseid-1.crypto.com:26657` for basic query now.
=> Testnet docs update (19-Oct)

docs/.vuepress/config.js, docs/resources/cosmos-grpc-docs.md
- Note that the `cosmos-grpc-docs.md ` file is a tool generated file
=> Added cosmos gRPC docs

docs/getting-started/croeseid-testnet.md, docs/getting-started/local-devnet.md, docs/wallets/cli.md
Instead of adding un-jail instruction, added instructions of transfer, staking & query balance. A note is also added at the end for redirecting people to chain-maind cli page.
=> Problem:(Fix #42) Added more instructions and reference to chain-maind cli page in the testnet docs

docs/getting-started/croeseid-testnet.md
For me and other members of the community on [Discord](https://discord.com/channels/783264383978569728/783264902613565450/789208334800388127),  we needed to add `gas-prices` to fix the `insufficient fee` error. 
Also, since we get 10 test CRO per day on the faucet,  I reduced the amount of the `create-validator` transaction, since a low amount worked for me.
=> Croeseid testnet getting-started: update create-validator transaction

docs/getting-started/croeseid-testnet.md, docs/getting-started/testnet-aws-1click.md, docs/getting-started/testnet-azure-1click.md
Solution:
- Update the "Getting started" and "1-Click" contents to v0.8.1-croeseid.
=> Problem: (fix#100) Testnet docs is not updated to v0.8.1

docs/getting-started/README.md, docs/getting-started/croeseid-testnet.md, docs/getting-started/local-devnet.md, docs/getting-started/testnet-aws-1click.md, docs/getting-started/testnet-azure-1click.md, docs/wallets/cli.md, docs/wallets/ledger.md
Updated `getting-started/croeseid-testnet.md` to v0.9.1-croeseid along with some links redirections.
=> Docs updates for Croeseid-v0.9.1-upgrade 

docs/getting-started/croeseid-testnet.md, docs/wallets/mainnet-address-generation.md
Fix #121 
- `croeseid-testnet.md`: 
Added instruction to verify the node is running/syncing by `chain-maind status`.
-  `mainnet-address-generation.md`:
Fixed "warning" and "tip" VuePress admonitions.
=> Problem:  (fix #121) No instruction to verify the node is running/syncing

docs/getting-started/croeseid-testnet.md
Align with changes in [home-brew-chain-maind](https://github.com/crypto-org-chain/homebrew-chain-maind/pull/10#pullrequestreview-613905007) by @allthatjazzleo : 
- Remove homebrew option for Croeseid testnet, where homebrew will be reserved for mainnet `chain-maind`.
=> Removing homebrew for Croeseid

docs/getting-started/mainnet.md
As discussed with @allthatjazzleo:
- Put crypto.org's nodes as `seeds` as defaultl;
- Add crypto.org's nodes to `persistent_peers` for state-sync users.
=> Mainnet Docs update

docs/getting-started/aws-1click.md, docs/getting-started/azure-1click.md, docs/getting-started/mainnet.md, docs/getting-started/upgrade_guide.md, docs/wallets/mainnet-address-generation.md
Added guide for `v1.2.1` upgrade.
=> Problem: (Fix #153) No guide for v1.2.1 upgrade

docs/chain-details/module_overview.md
Previously updated the gov process link in "module gov", updating it in "module overview" gov section as well.
=> Update gov process link under module overview

docs/getting-started/upgrade_guide.md
The suggested removed part is the old update and not really necessary to be in this mainnet upgrade tutorial.
=> Remove the Old Tutorial

docs/getting-started/aws-1click.md, docs/getting-started/azure-1click.md, docs/getting-started/mainnet.md, docs/wallets/mainnet-address-generation.md
1. ` docs/getting-started/aws-1click.md` and `docs/getting-started/azure-1click.md `
- Placed the warning and recommends at the top of the doc.
2. `docs/getting-started/mainnet.md `
- Added descriptions for required flag where sending the `create-validator` transaction. 
3. Some minor fixes for the binary upgrade
=> [7th June] chain-docs updates

docs/.vuepress/config.js, docs/getting-started/README.md, docs/getting-started/mainnet.md, docs/getting-started/mainnet_validator.md
Separating the guide for building a full node/ validator: 
For full node guide:
1. Start the node with the older binary version `v1.2.1`; 
1. Sync-up with the blockchain until it reaches the target upgrade block height `922,363`;
1. Update the binary to `v2.0.1` and start the node again.
For validator guide: 
1. Begin with the binary `v2.0.1` and join the network by *"STATE-SYNC"*
(link it to full node guide if users want a validator with full data)
=> Separated guide for building a full node/ validator 

docs/.vuepress/config.js, docs/getting-started/README.md, docs/resources/blocks-and-transactions.md, docs/resources/chain-integration.md, docs/resources/node-and-rpc-setup-notes.md
Migrating [chain-integration](https://github.com/crypto-org-chain/chain-integration) content  to `chain-docs`.
Afterwards, updates and maintenance of the integration documentation continue here.
=> Migrating `chain-integration` content  to `chain-docs`

docs/resources/chain-integration.md
Fix links for gRPC query methods
=> Fix links for gRPC query methods

docs/chain-details/module_overview.md
The same content for "supply" already exists at the bottom of the page, while it appears again between "slashing" and "staking".
Removing the repetitive "supply" part.
=> Removing the repetitive "supply" content

docs/getting-started/croeseid-testnet.md, docs/getting-started/mainnet_validator.md
Add note to explain how to get the 'validator-addr' with bech32 Prefix.
=> Problem: (Fix #202)Missing instruction on how to get the 'validator-addr' with bech32 prefix

docs/getting-started/croeseid-testnet.md
=> Add instructions on how to make the unsigned macOS binary runnable.

docs/getting-started/mainnet.md
update the docs for the network upgrade `v1.*.*` to `v2.1.2`.
=> 2.1.2 guide update
