docs/getting-started/croeseid-testnet.md

Problem: missing sed that work on both OSX and linux

---

docs/getting-started/croeseid-testnet.md

Solution: (Fix #21) Add instructions to update the minimum gas prices

Problem: minimum gas prices not put by default

---

docs/getting-started/croeseid-testnet.md
docs/wallets/cli.md

- Fixed sha256 hash check command;
- Update the link of the public fullnodel;
- Remove broken links.

Testnet doc updates,20-Oct

---

.github/workflows/chain-docs.yml

Uncomment scan job as repo is public

fix ci scan when repo is public

---

docs/getting-started/assets/signature_checking/check-validator-up.sh
docs/getting-started/croeseid-testnet.md

Solution:
- Increase the validator list to `300 per_page`;
- Fix the public key path.

Problem (fix#30) : `signature_checking.sh` is not working.

---

docs/getting-started/local-devnet.md
docs/wallets/cli.md

Solution:
- Updated the docs for starting pystarport;
- Added basic staking-related operations.

Problem: Missing send first tx tutorial

---

docs/getting-started/croeseid-testnet.md

Solution: add steps for using systemd service

Problem: (fix #37)Missing service file for chain-maind

---

docs/getting-started/croeseid-testnet.md

Solution: Update to latest release of rc1

Problem: Using previous release of 0.7.0_rc0

---

docs/.vuepress/config.js
docs/wallets/ledger.md

Solution: (Fix #43) Adde Ledger guide with basic operation instructions

Problem: Missing Ledger tutorial

---

docs/getting-started/croeseid-testnet.md

Solution: add guide for state-sync configuration

Problem: (fix #4)Missing documentation for state sync

---

README.md

Fix the README.md chain-docs logo

Fixing the chain-docs logo

---

docs/getting-started/local-devnet.md

Solution:
- update content
- add section "Build with nix"

Problem (fix #47): Outdated Devnet guide with pystarport

---

docs/getting-started/local-devnet.md

Problem:(Fix #50) No mentioning of pystarport start to keep block status

---

docs/chain-details/architecture.md
docs/chain-details/module_staking.md
docs/getting-started/README.md
docs/getting-started/assets/signature_checking/check-validator-up.sh
docs/getting-started/croeseid-testnet.md

Solution: Aligning the wording to prevent confusion it may have caused.

Aligning the wording of "validator" 

---

docs/getting-started/croeseid-testnet.md

Solution: (Fix #57) change to use rc2

Problem: setup is using previous rc1 release

---

docs/.vuepress/config.js
docs/chain-details/introduction.md
docs/chain-details/module_overview.md

Solution:
- Fixed text format;
- Grouped all module sections under "Modules"

Problem:(Fix #55):minor formatting issues

---

docs/getting-started/croeseid-testnet.md
docs/getting-started/testnet-azure-1click.md

**Solution:**
- Redirect to the discord channel.

Problem: (Fix#67) Community chat is not redirected to the Discord channel

---

docs/getting-started/croeseid-testnet.md
docs/wallets/cli.md

- Fix cli show keys commands;
- Update `create-validator` tx, added auto gas flags.

Quick update on getting started for Croeseid testnet

---

docs/getting-started/README.md
docs/getting-started/croeseid-testnet-nix.md

Problem: no instructions to setup testnet node with nix

---

docs/.vuepress/config.js
docs/getting-started/croeseid-testnet-nix.md

Problem: nix doc not linked in sidebar

---

docs/wallets/cli.md

This pr adds missing "keys" command in the wallet show examples.

Updates wallets docs

---

docs/getting-started/croeseid-testnet-nix.md

Solution:
- update commit hash to fix state sync rpc url

Problem: nix instruction failed to work

---

docs/getting-started/croeseid-testnet.md

Solution: update STATE-SYNC configuration

Problem: (fix #85) STATE-SYNC configuration is not updated

---

docs/.vuepress/config.js

**Solution**: Recover the explorer link.

Problem: Explorer link is missing from the navbar

---

docs/.vuepress/config.js
docs/.vuepress/theme/components/AlgoliaSearchBox.vue
docs/.vuepress/theme/components/Navbar.vue
docs/.vuepress/theme/layouts/Layout.vue

Solution: (Fix #92) Fix menu button and responsive layout

Problem: Menu button is not working on mobile

---

docs/chain-details/introduction.md
docs/chain-details/module_bank.md
docs/chain-details/module_distribution.md
docs/chain-details/module_gov.md
docs/chain-details/module_overview.md
docs/chain-details/module_slashing.md
docs/chain-details/module_staking.md
docs/getting-started/README.md
docs/getting-started/advanced-tmkms-integration.md
docs/getting-started/croeseid-testnet-nix.md
docs/getting-started/croeseid-testnet.md
docs/getting-started/local-devnet.md
docs/getting-started/testnet-aws-1click.md
docs/getting-started/testnet-azure-1click.md

- Added useful links;
- Removed `multisend-1tomany` from the cli remark; 
- Some typo fixes.

Adding useful links and typo fix 

---

docs/getting-started/croeseid-testnet.md

as title, fixing an invalid link

Problem: Invalid same page link

---

docs/chain-details/parameters.md

Added the notes for ambiguous "string" type for denominations (bond_denom and mint_denom)

Aw126 added denomnote

---

.github/workflows/chain-docs.yml
docs/getting-started/advanced-tmkms-integration.md

Solution: update to use tmkms-light repo and change setup for tmkms enclave
also fix #98

Problem: (fix #109) Advanced TMKMS Integration is not updated

---

docs/getting-started/croeseid-testnet-nix.md

Solution:
- update the git commit ref

Problem: nix instructions not update to recent release

---

docs/getting-started/croeseid-testnet.md

Problem: (fix #130)Problem: network configuration sed command not show correctly on website

---

docs/wallets/ledger_desktop_wallet.md

Adding Discord channel link to the Ledger-Desktop wallet Docs.

Adding Discord channel link to the Ledger-Desktop wallet Docs 

---

docs/.vuepress/theme/components/Footer.vue

Problem (Fix #137): Footer discord & menu not updated

---

docs/wallets/mainnet-address-generation.md

Updated rebranding wordings. 
Will send the updated imgs to you for uploading because of the file upload permission. @lezzokafka @tomtau

updated rebranding wordings

---

docs/wallets/ledger_desktop_wallet.md

Will send the new imgs for s2-5 to @lezzokafka for uploading because of my file upload permission, thanks.

Revise wordings corresponding to recent update/rebranding

---

docs/chain-details/module_gov.md

Update refund rule to match with other docs and minor adjustments.

Update Refund Rule to be Matched with Other Docs

---

docs/chain-details/govprocess.md

A subpage for governance process and details.

Add a Subpage for Governance Process

---

docs/getting-started/mainnet.md
docs/getting-started/upgrade_guide.md

Added Canis Major (v2.0.0) upgrade guide

Canis Major (v2.0.0) upgrade guide

---

docs/chain-details/chain-id.md
docs/getting-started/advanced-tmkms-integration.md
docs/getting-started/aws-1click.md
docs/getting-started/azure-1click.md
docs/getting-started/croeseid-testnet.md
docs/wallets/ledger.md

Update the testnet docs for `testnet-croeseid-3`

Testnet "testnet-croeseid-3" docs update

---

docs/wallets/keplr_ledger_guide.md

* Clarify why Keplr permissions
* Minor wording change to leave a small amount of CRO for future tx fees

Info on permissions and minor changes

---

docs/getting-started/nft-guide.md

Remove the term, as "deno" is a typo and repetitive with another term of "denom".

Remove the unwanted part

---

docs/getting-started/croeseid-testnet.md
docs/getting-started/mainnet.md
docs/getting-started/mainnet_validator.md

The reminders and tips are mainly about:
1. Using the specific binary for specific networks.
2. How to generate new validator key.
3. How to fix `too many opened files...` error.

Added a few reminders and tips in croeseid-testnet.md, mainnet.md and mainnet_validator.md

---

docs/getting-started/mainnet_validator.md

The steps jumped from 3.1 to 3.5 in the original version.

Correcting the sorting number in Step 3

---

docs/wallets/keplr_IBC_guide.md

Update the warming msg on verifying if an IBC channel is active before performing IBC transactions.

Update the warming msg on IBC transactions

---

docs/getting-started/mainnet_validator.md

Corresponding to https://github.com/crypto-org-chain/chain-docs/issues/234

Update the doc with the latest binary version v.3.3.3

---

docs/getting-started/mainnet.md
docs/getting-started/mainnet_validator.md

While attempting to set up a validator node, I ran into a few issues caused by some out of date docs. I'd like to make this clearer for others in the future.

Additional clarification for setting up a validator/full node

---

docs/wallets/ledger_desktop_wallet.md

- https://github.com/crypto-com/chain-desktop-wallet/issues/896'

Add Ledger Connection Troubleshoot section

---

docs/getting-started/mainnet.md

Adding network updates in Step 0, complements to the below steps and *Getting ready - "DRACO II" second network upgrade* section.

Clarify Step 0 on both network updates

---

docs/getting-started/mainnet.md

The suggested removed part is optional while it can look confusing to users. Now update to remove this unnecessary part.

Remove the unnecessary part for Quicksync guide

---

docs/wallets/multisig-account.md

A short guide how to setup a multisign acc and sign multisigned tx.

Add a guide for a multisign account
